name: backendtf
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - aom=3.4.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.2.0
  - bidict=0.22.1
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cycler=0.11.0
  - dnspython=2.3.0
  - eventlet=0.33.3
  - ffmpeg=4.4.2
  - flask=2.0.3
  - flask-cors=3.0.10
  - flask-socketio=5.3.3
  - flatbuffers=2.0.8
  - fontconfig=2.13.94
  - fonttools=4.39.3
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - google-auth=2.16.3
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - greenlet=2.0.2
  - grpc-cpp=1.46.4
  - grpcio=1.46.4
  - h5py=3.7.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib-resources=5.12.0
  - importlib_resources=5.12.0
  - itsdangerous=2.0.1
  - jasper=2.0.33
  - jinja2=3.0.3
  - jpeg=9e
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.51.0
  - libopenblas=0.3.21
  - libopencv=4.5.5
  - libpng=1.6.39
  - libprotobuf=3.20.2
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=16.0.0
  - markdown=3.4.3
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - multidict=6.0.4
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.8.1
  - numpy=1.24.2
  - oauthlib=3.2.2
  - opencv=4.5.5
  - openh264=2.2.0
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - p11-kit=0.24.1
  - packaging=23.0
  - pcre2=10.40
  - pillow=9.2.0
  - pip=23.0.1
  - pixman=0.38.0
  - platformdirs=3.2.0
  - pooch=1.7.0
  - protobuf=3.20.2
  - pthread-stubs=0.4
  - py-opencv=4.5.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.6.0
  - pyopenssl=23.1.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-engineio=4.4.0
  - python-flatbuffers=23.1.21
  - python-socketio=5.8.0
  - python_abi=3.9
  - pyu2f=0.1.5
  - re2=2022.06.01
  - readline=8.2
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.10.1
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.1
  - svt-av1=1.1.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.2.0
  - tk=8.6.12
  - tornado=6.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - werkzeug=2.2.3
  - wheel=0.35.1
  - wrapt=1.15.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.10
  - yarl=1.8.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
